export const GET_QUOTE_FETCHING = "GET_QUOTE_FETCHING";
export const GET_QUOTE_FETCHED = "GET_QUOTE_FETCHED";
export const GET_QUOTE_ERROR = "GET_QUOTE_ERROR";
export const SAVE_QUOTE_DATA = "SAVE_QUOTE_DATA";
